tmp=getTitle();
run("Invert");

run("Split Channels");
selectWindow("C3-"+tmp);
rename("B");
selectWindow("C2-"+tmp);
rename("G");
selectWindow("C1-"+tmp);
rename("R");
imageCalculator("Average create 32-bit", "R","G");
rename("AvgGR");
imageCalculator("Subtract create 32-bit", "AvgGR","B");
rename("InSitu");
selectWindow("AvgGR");
close();
selectWindow("B");
setAutoThreshold("Default dark");
run("Convert to Mask");
rename("WormMask");
run("Analyze Particles...", "size=10000-Infinity circularity=0.00-1.00 show=Masks clear");
rename("tmp");
selectWindow("WormMask");
close();
selectWindow("tmp");
rename("WormMask");
run("Calculator Plus", "i1=InSitu i2=G operation=[Scale: i2 = i1 x k1 + k2] k1=1 k2=10000 create");
rename("tmp");
imageCalculator("Multiply create 32-bit", "tmp","WormMask");
rename("MaskedInSitu");
selectWindow("tmp");
close();
selectWindow("MaskedInSitu");
run("Duplicate...", "title=InSituMask");

//setAutoThreshold("MaxEntropy dark");

setThreshold(2613000.0000, 3315000.0000);
run("Convert to Mask");
run("Erode");
run("Erode");
run("Erode");
run("Erode");
run("Dilate");
run("Dilate");
run("Dilate");
imageCalculator("XOR create 32-bit", "WormMask","InSituMask");
rename("InSituInvMask");
imageCalculator("Multiply create 32-bit", "MaskedInSitu","InSituMask");
rename("Pharynx");
imageCalculator("Multiply create 32-bit", "MaskedInSitu","InSituInvMask");
rename("NonPharynx");
selectWindow("InSitu");
close();
selectWindow("R");
close();
selectWindow("G");
close();
selectWindow("MaskedInSitu");
close();
